In [1]:
# | Goal                                  | Meaning                   |
# | ------------------------------------- | ------------------------- |
# | train ML model                        | predict default risk      |
# | validate engineered features          | see what actually matters |
# | explain feature importance            | enterprise explainability |
# | evaluate predictive power             | ROC-AUC, classification   |
# | identify strongest behavioral signals | business intelligence     |

In [2]:
# IMPORT LIBRARIES ⭐⭐⭐



import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (

    classification_report,

    roc_auc_score,

    confusion_matrix
)

In [3]:
# ============================================================
# LOAD ENGINEERED DATASET
# ============================================================

application_train = pd.read_csv(

    "../data/processed/engineered_credit_risk_dataset.csv"
)

application_train.shape

(307511, 145)

In [4]:
# SELECT FEATURES ⭐⭐⭐

# Now we build:

# modeling dataset.



feature_columns = [

    "ANNUITY_TO_INCOME",

    "CREDIT_TO_INCOME",

    "FREE_CASH_FLOW",

    "DEBT_TO_INCOME",

    "DEBT_PER_BUREAU_RECORD",

    "APPLICATIONS_PER_INCOME",

    "LATE_PAYMENT_COUNT",

    "MISSED_PAYMENTS_PER_LOAN",

    "AVG_PAYMENT_DELAY",

    "RECENT_LATE_PAYMENT_COUNT",

    "REPAYMENT_STABILITY",

    "YEARS_EMPLOYED",

    "EMPLOYMENT_TO_AGE_RATIO",

    "BEHAVIORAL_RISK_SCORE"
]

In [5]:
# BUILD X AND y ⭐⭐⭐
X = application_train[
    feature_columns
]

y = application_train[
    "TARGET"
]

In [6]:
# HANDLE MISSING VALUES ⭐⭐⭐

X = X.fillna(0)

In [7]:
# TRAIN / TEST SPLIT ⭐⭐⭐

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

In [8]:
# IMPORT SMOTE ⭐⭐⭐

from imblearn.over_sampling import SMOTE

In [9]:
# APPLY SMOTE ONLY TO TRAINING DATA ⭐⭐⭐
smote = SMOTE(

    random_state=42
)

X_train_resampled, y_train_resampled = (

    smote.fit_resample(

        X_train,
        y_train
    )
)

In [11]:
# VALIDATE BALANCE ⭐⭐⭐


print(

    y_train.value_counts()
)

print(
    "----------------------"
)

print(

    y_train_resampled.value_counts()
)

TARGET
0    226148
1     19860
Name: count, dtype: int64
----------------------
TARGET
0    226148
1    226148
Name: count, dtype: int64

In [15]:
# MPORT STANDARD SCALER ⭐⭐⭐
from sklearn.preprocessing import StandardScaler
# SCALE TRAIN + TEST ⭐⭐⭐

# Run BEFORE model training:

# ============================================================
# FEATURE SCALING
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(

    X_train_resampled
)

X_test_scaled = scaler.transform(

    X_test
)

In [12]:
# TRAIN LOGISTIC REGRESSION ⭐⭐⭐

# ============================================================
# LOGISTIC REGRESSION MODEL
# ============================================================
# WHY LOGISTIC REGRESSION FIRST ⭐⭐⭐

# Because:
# coefficients are:

# explainable.

# This is VERY important in banking.

# Unlike black-box models,
# you can directly inspect:

# feature direction,
# feature impact,
# risk drivers.

# THIS matters enormously in:

# underwriting,
# compliance,
# model governance,
# regulatory reviews.

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(

    max_iter=1000,

    random_state=42
)

model.fit(

    X_train_resampled,

    y_train_resampled
)

print(
    "Model training completed."
)

Model training completed.

/home/muzzi/first_project/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [13]:
# GENERATE PREDICTIONS ⭐⭐⭐

# After training:

# ============================================================
# MODEL PREDICTIONS
# ============================================================

predictions = model.predict(

    X_test
)

probabilities = model.predict_proba(

    X_test
)[:,1]

print(
    "Predictions generated successfully."
)

Predictions generated successfully.

In [14]:
# CLASSIFICATION REPORT ⭐⭐⭐

# Now evaluate model performance.

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

from sklearn.metrics import classification_report

print(

    classification_report(

        y_test,

        predictions
    )
)

              precision    recall  f1-score   support

           0       0.93      0.51      0.66     56538
           1       0.09      0.54      0.15      4965

    accuracy                           0.51     61503
   macro avg       0.51      0.52      0.41     61503
weighted avg       0.86      0.51      0.62     61503

In [16]:
# RETRAIN MODEL ⭐⭐⭐
# Now retrain using:
# scaled data.

# ============================================================
# LOGISTIC REGRESSION MODEL
# ============================================================

model = LogisticRegression(

    max_iter=3000,

    random_state=42
)

model.fit(

    X_train_scaled,

    y_train_resampled
)

print(
    "Model training completed."
)

Model training completed.

In [17]:
# PREDICT USING SCALED TEST SET ⭐⭐⭐

# VERY important.

# ============================================================
# MODEL PREDICTIONS
# ============================================================

predictions = model.predict(

    X_test_scaled
)

probabilities = model.predict_proba(

    X_test_scaled
)[:,1]

In [18]:
# CLASSIFICATION REPORT ⭐⭐⭐

# Now evaluate model performance.

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

from sklearn.metrics import classification_report

print(

    classification_report(

        y_test,

        predictions
    )
)

              precision    recall  f1-score   support

           0       0.93      0.60      0.73     56538
           1       0.09      0.47      0.16      4965

    accuracy                           0.59     61503
   macro avg       0.51      0.54      0.44     61503
weighted avg       0.86      0.59      0.69     61503

In [19]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(
    y_test,
    probabilities
)

print(
    f"ROC AUC Score: {auc:.4f}"
)

ROC AUC Score: 0.5565

In [21]:
## XGboost model

# MPORT LIBRARIES ⭐⭐⭐


# ============================================================
# XGBOOST + SHAP IMPORTS
# ============================================================

from xgboost import XGBClassifier

import shap

In [22]:
# TRAIN XGBOOST MODEL ⭐⭐⭐

# ============================================================
# XGBOOST MODEL
# ============================================================

xgb_model = XGBClassifier(

    n_estimators=200,

    max_depth=6,

    learning_rate=0.05,

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

xgb_model.fit(

    X_train_resampled,

    y_train_resampled
)

print(
    "XGBoost training completed."
)

XGBoost training completed.

In [23]:
# GENERATE PREDICTIONS ⭐⭐⭐
# ============================================================
# XGBOOST PREDICTIONS
# ============================================================

xgb_predictions = xgb_model.predict(

    X_test
)

xgb_probabilities = xgb_model.predict_proba(

    X_test
)[:,1]

print(
    "Predictions generated successfully."
)

Predictions generated successfully.

In [24]:
# STEP 5 — EVALUATE MODEL ⭐⭐⭐
# CLASSIFICATION REPORT ⭐⭐⭐
# ============================================================
# XGBOOST CLASSIFICATION REPORT
# ============================================================

print(

    classification_report(

        y_test,

        xgb_predictions
    )
)

              precision    recall  f1-score   support

           0       0.92      0.99      0.95     56538
           1       0.15      0.02      0.03      4965

    accuracy                           0.91     61503
   macro avg       0.54      0.50      0.49     61503
weighted avg       0.86      0.91      0.88     61503

In [25]:
# ROC-AUC ⭐⭐⭐ MOST IMPORTANT
# ============================================================
# XGBOOST ROC-AUC
# ============================================================

xgb_auc = roc_auc_score(

    y_test,

    xgb_probabilities
)

print(
    f"XGBoost ROC AUC: {xgb_auc:.4f}"
)

XGBoost ROC AUC: 0.5916

In [39]:
# ============================================================
# LOAD UPDATED ENGINEERED DATASET
# ============================================================

application_train = pd.read_csv(

    "../data/processed/engineered_credit_risk_dataset.csv"
)

application_train.shape

(307511, 169)

In [40]:

# ============================================================
# FEATURE SELECTION
# ============================================================
# ============================================================
# FINAL ENTERPRISE FEATURE SET ⭐⭐⭐
# ============================================================
# ============================================================
# FINAL ENTERPRISE FEATURE SET ⭐⭐⭐
# ============================================================

feature_columns = [

    # ========================================================
    # AFFORDABILITY FEATURES
    # ========================================================

    "ANNUITY_TO_INCOME",

    "CREDIT_TO_INCOME",

    "FREE_CASH_FLOW",

    "DEBT_TO_INCOME",

    "CREDIT_TO_ANNUITY_RATIO",

    "CREDIT_TO_GOODS_RATIO",

    "DOWN_PAYMENT",


    # ========================================================
    # EXTERNAL RISK / EXT_SOURCE FEATURES ⭐⭐⭐
    # ========================================================

    "EXT_SOURCE_1",

    "EXT_SOURCE_2",

    "EXT_SOURCE_3",

    "EXT_SOURCE_MEAN",

    "EXT_SOURCE_STD",

    "CREDIT_EXT_RATIO",


    # ========================================================
    # LEVERAGE + EXPOSURE FEATURES
    # ========================================================

    "DEBT_PER_BUREAU_RECORD",

    "OVERDUE_PER_BUREAU_RECORD",

    "ACTIVE_DEBT_RATIO",

    "MEAN_DAYS_CREDIT",

    "LAST_ACTIVE_DAYS_CREDIT",


    # ========================================================
    # BORROWING BEHAVIOR FEATURES
    # ========================================================

    "APPLICATIONS_PER_INCOME",

    "PREVIOUS_APPLICATION_COUNT",

    "RECENT_APPLICATION_COUNT",

    "BORROWING_ACCELERATION_RATIO",


    # ========================================================
    # REPAYMENT BEHAVIOR FEATURES
    # ========================================================

    "LATE_PAYMENT_COUNT",

    "MISSED_PAYMENTS_PER_LOAN",

    "AVG_PAYMENT_DELAY",

    "AVG_PAYMENT_DEFICIT",

    "REPAYMENT_STABILITY",


    # ========================================================
    # TEMPORAL REPAYMENT FEATURES
    # ========================================================

    "LATE_PAYMENTS_LAST_90D",

    "AVG_PAYMENT_DELAY_LAST_90D",

    "RECENT_TO_HISTORICAL_DELAY_RATIO",

    "RECENT_DELAY_TREND",

    "RECENT_PAYMENT_DEFICIT",

    "PAYMENT_DEFICIT_TREND",

    "RECENT_PAYMENT_STABILITY",


    # ========================================================
    # EMPLOYMENT + DEMOGRAPHIC FEATURES
    # ========================================================

    "YEARS_EMPLOYED",

    "EMPLOYMENT_TO_AGE_RATIO",

    "AGE_YEARS",


    # ========================================================
    # HISTORICAL REPAYMENT CAPACITY
    # ========================================================

    "MAX_INSTALLMENT",

    "ANNUITY_TO_MAX_INSTALLMENT_RATIO",


    # ========================================================
    # COMPOSITE RISK FEATURES
    # ========================================================

    "BEHAVIORAL_RISK_SCORE"
]
# ============================================================
# BUILD MODELING DATASET
# ============================================================

X = application_train[
    feature_columns
]

y = application_train[
    "TARGET"
]

# ------------------------------------------------------------
# HANDLE NULLS
# ------------------------------------------------------------

X = X.fillna(0)


# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

print(y_train.value_counts())


# ============================================================
# HANDLE CLASS IMBALANCE — SMOTE
# ============================================================

smote = SMOTE(

    random_state=42
)

X_train_resampled, y_train_resampled = (

    smote.fit_resample(

        X_train,
        y_train
    )
)

print("----------------------------")

print(y_train_resampled.value_counts())

TARGET
0    226148
1     19860
Name: count, dtype: int64
----------------------------
TARGET
0    226148
1    226148
Name: count, dtype: int64

In [41]:

# ============================================================
# XGBOOST MODEL
# ============================================================

xgb_model = XGBClassifier(

    n_estimators=300,

    max_depth=6,

    learning_rate=0.05,

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

xgb_model.fit(

    X_train_resampled,

    y_train_resampled
)

print(
    "XGBoost training completed."
)


# ============================================================
# PREDICTIONS
# ============================================================

xgb_predictions = xgb_model.predict(

    X_test
)

xgb_probabilities = xgb_model.predict_proba(

    X_test
)[:,1]

print(
    "Predictions generated successfully."
)


# ============================================================
# CLASSIFICATION REPORT
# ============================================================

print(
    "\nCLASSIFICATION REPORT\n"
)

print(

    classification_report(

        y_test,

        xgb_predictions
    )
)


# ============================================================
# ROC AUC SCORE
# ============================================================

xgb_auc = roc_auc_score(

    y_test,

    xgb_probabilities
)

print(
    f"\nXGBoost ROC AUC: {xgb_auc:.4f}"
)


# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(

    y_test,

    xgb_predictions
)

print(
    "\nCONFUSION MATRIX\n"
)

print(cm)

XGBoost training completed.
Predictions generated successfully.

CLASSIFICATION REPORT

              precision    recall  f1-score   support

           0       0.92      0.99      0.96     56538
           1       0.41      0.05      0.09      4965

    accuracy                           0.92     61503
   macro avg       0.67      0.52      0.52     61503
weighted avg       0.88      0.92      0.89     61503


XGBoost ROC AUC: 0.7492

CONFUSION MATRIX

[[56195   343]
 [ 4723   242]]

In [46]:
# ============================================================
# CUSTOM THRESHOLD PREDICTIONS
# ============================================================

custom_predictions = (

    xgb_probabilities > 0.20
).astype(int)

print(

    classification_report(

        y_test,

        custom_predictions
    )
)


# ============================================================
# ROC AUC SCORE
# ============================================================

xgb_auc = roc_auc_score(

    y_test,

    xgb_probabilities
)

print(
    f"\nXGBoost ROC AUC: {xgb_auc:.4f}"
)


# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(

    y_test,

    custom_predictions
)

print(cm)

              precision    recall  f1-score   support

           0       0.95      0.87      0.90     56538
           1       0.22      0.43      0.29      4965

    accuracy                           0.83     61503
   macro avg       0.58      0.65      0.60     61503
weighted avg       0.89      0.83      0.85     61503


XGBoost ROC AUC: 0.7492
[[48999  7539]
 [ 2837  2128]]

In [47]:
# ============================================================
# XGBOOST ENTERPRISE OPTIMIZATION ⭐⭐⭐
# OPTIMIZE FOR:
# - ROC AUC
# - RECALL
# - PRECISION
# - F1 SCORE
#
# WITH:
# custom operational threshold
# ============================================================

from sklearn.model_selection import ParameterGrid

from sklearn.metrics import (

    roc_auc_score,

    precision_score,

    recall_score,

    f1_score
)

# ============================================================
# PARAMETER GRID
# ============================================================

param_grid = {

    "max_depth": [4, 6, 8],

    "learning_rate": [0.03, 0.05, 0.1],

    "n_estimators": [200, 300],

    "subsample": [0.8],

    "colsample_bytree": [0.8]
}

# ============================================================
# THRESHOLDS TO TEST ⭐⭐⭐
# ============================================================

thresholds = [

    0.10,

    0.15,

    0.20,

    0.25,

    0.30
]

# ============================================================
# STORE RESULTS
# ============================================================

results = []

# ============================================================
# HYPERPARAMETER + THRESHOLD SEARCH
# ============================================================

for params in ParameterGrid(param_grid):

    print(f"\nTesting Parameters: {params}")

    # --------------------------------------------------------
    # TRAIN MODEL
    # --------------------------------------------------------

    model = XGBClassifier(

        random_state=42,

        eval_metric="logloss",

        **params
    )

    model.fit(

        X_train_resampled,

        y_train_resampled
    )

    # --------------------------------------------------------
    # PREDICT PROBABILITIES
    # --------------------------------------------------------

    probabilities = model.predict_proba(
        X_test
    )[:,1]

    # --------------------------------------------------------
    # ROC AUC
    # --------------------------------------------------------

    auc = roc_auc_score(

        y_test,

        probabilities
    )

    # --------------------------------------------------------
    # TEST DIFFERENT THRESHOLDS
    # --------------------------------------------------------

    for threshold in thresholds:

        predictions = (

            probabilities > threshold
        ).astype(int)

        precision = precision_score(

            y_test,

            predictions,

            zero_division=0
        )

        recall = recall_score(

            y_test,

            predictions
        )

        f1 = f1_score(

            y_test,

            predictions
        )

        results.append({

            "max_depth": params["max_depth"],

            "learning_rate": params["learning_rate"],

            "n_estimators": params["n_estimators"],

            "threshold": threshold,

            "roc_auc": auc,

            "precision": precision,

            "recall": recall,

            "f1_score": f1
        })

        print(

            f"Threshold={threshold} | "
            f"AUC={auc:.4f} | "
            f"Precision={precision:.4f} | "
            f"Recall={recall:.4f} | "
            f"F1={f1:.4f}"
        )

    print("------------------------------------------")

# ============================================================
# RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)

# ============================================================
# SORT BY F1 SCORE ⭐⭐⭐
# ============================================================

results_df = results_df.sort_values(

    by=[

        "f1_score",

        "roc_auc"
    ],

    ascending=False
)

# ============================================================
# BEST RESULTS
# ============================================================

results_df.head(20)

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.03, 'max_depth': 4, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7242 | Precision=0.1006 | Recall=0.9311 | F1=0.1815
Threshold=0.15 | AUC=0.7242 | Precision=0.1202 | Recall=0.8330 | F1=0.2101
Threshold=0.2 | AUC=0.7242 | Precision=0.1378 | Recall=0.7253 | F1=0.2315
Threshold=0.25 | AUC=0.7242 | Precision=0.1551 | Recall=0.6242 | F1=0.2485
Threshold=0.3 | AUC=0.7242 | Precision=0.1733 | Recall=0.5331 | F1=0.2615
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.03, 'max_depth': 4, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7286 | Precision=0.1133 | Recall=0.8731 | F1=0.2006
Threshold=0.15 | AUC=0.7286 | Precision=0.1357 | Recall=0.7543 | F1=0.2300
Threshold=0.2 | AUC=0.7286 | Precision=0.1554 | Recall=0.6352 | F1=0.2497
Threshold=0.25 | AUC=0.7286 | Precision=0.1772 | Recall=0.5345 | F1=0.2661
Threshold=0.3 | AUC=0.7286 | Precision=0.1979 | Recall=0.4298 | F1=0.2710
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.03, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7331 | Precision=0.1173 | Recall=0.8564 | F1=0.2064
Threshold=0.15 | AUC=0.7331 | Precision=0.1424 | Recall=0.7233 | F1=0.2380
Threshold=0.2 | AUC=0.7331 | Precision=0.1675 | Recall=0.6073 | F1=0.2626
Threshold=0.25 | AUC=0.7331 | Precision=0.1911 | Recall=0.4931 | F1=0.2754
Threshold=0.3 | AUC=0.7331 | Precision=0.2115 | Recall=0.3815 | F1=0.2721
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.03, 'max_depth': 6, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7409 | Precision=0.1342 | Recall=0.7907 | F1=0.2295
Threshold=0.15 | AUC=0.7409 | Precision=0.1634 | Recall=0.6423 | F1=0.2605
Threshold=0.2 | AUC=0.7409 | Precision=0.1937 | Recall=0.5176 | F1=0.2819
Threshold=0.25 | AUC=0.7409 | Precision=0.2171 | Recall=0.3970 | F1=0.2807
Threshold=0.3 | AUC=0.7409 | Precision=0.2457 | Recall=0.2965 | F1=0.2687
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.03, 'max_depth': 8, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7410 | Precision=0.1312 | Recall=0.7962 | F1=0.2253
Threshold=0.15 | AUC=0.7410 | Precision=0.1602 | Recall=0.6532 | F1=0.2573
Threshold=0.2 | AUC=0.7410 | Precision=0.1895 | Recall=0.5321 | F1=0.2795
Threshold=0.25 | AUC=0.7410 | Precision=0.2134 | Recall=0.4068 | F1=0.2799
Threshold=0.3 | AUC=0.7410 | Precision=0.2472 | Recall=0.3148 | F1=0.2769
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.03, 'max_depth': 8, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7485 | Precision=0.1472 | Recall=0.7249 | F1=0.2447
Threshold=0.15 | AUC=0.7485 | Precision=0.1839 | Recall=0.5813 | F1=0.2794
Threshold=0.2 | AUC=0.7485 | Precision=0.2180 | Recall=0.4508 | F1=0.2938
Threshold=0.25 | AUC=0.7485 | Precision=0.2507 | Recall=0.3392 | F1=0.2883
Threshold=0.3 | AUC=0.7485 | Precision=0.2850 | Recall=0.2459 | F1=0.2640
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 4, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7297 | Precision=0.1179 | Recall=0.8504 | F1=0.2070
Threshold=0.15 | AUC=0.7297 | Precision=0.1414 | Recall=0.7215 | F1=0.2365
Threshold=0.2 | AUC=0.7297 | Precision=0.1634 | Recall=0.6032 | F1=0.2571
Threshold=0.25 | AUC=0.7297 | Precision=0.1847 | Recall=0.4973 | F1=0.2694
Threshold=0.3 | AUC=0.7297 | Precision=0.2062 | Recall=0.3887 | F1=0.2695
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 4, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7373 | Precision=0.1312 | Recall=0.7905 | F1=0.2251
Threshold=0.15 | AUC=0.7373 | Precision=0.1592 | Recall=0.6427 | F1=0.2552
Threshold=0.2 | AUC=0.7373 | Precision=0.1891 | Recall=0.5235 | F1=0.2778
Threshold=0.25 | AUC=0.7373 | Precision=0.2128 | Recall=0.3998 | F1=0.2778
Threshold=0.3 | AUC=0.7373 | Precision=0.2387 | Recall=0.2971 | F1=0.2647
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7417 | Precision=0.1387 | Recall=0.7672 | F1=0.2350
Threshold=0.15 | AUC=0.7417 | Precision=0.1700 | Recall=0.6161 | F1=0.2665
Threshold=0.2 | AUC=0.7417 | Precision=0.2001 | Recall=0.4884 | F1=0.2839
Threshold=0.25 | AUC=0.7417 | Precision=0.2249 | Recall=0.3712 | F1=0.2801
Threshold=0.3 | AUC=0.7417 | Precision=0.2556 | Recall=0.2777 | F1=0.2662
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7492 | Precision=0.1508 | Recall=0.7192 | F1=0.2493
Threshold=0.15 | AUC=0.7492 | Precision=0.1874 | Recall=0.5625 | F1=0.2811
Threshold=0.2 | AUC=0.7492 | Precision=0.2201 | Recall=0.4286 | F1=0.2909
Threshold=0.25 | AUC=0.7492 | Precision=0.2538 | Recall=0.3212 | F1=0.2836
Threshold=0.3 | AUC=0.7492 | Precision=0.2926 | Recall=0.2340 | F1=0.2601
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7496 | Precision=0.1514 | Recall=0.7158 | F1=0.2499
Threshold=0.15 | AUC=0.7496 | Precision=0.1881 | Recall=0.5635 | F1=0.2820
Threshold=0.2 | AUC=0.7496 | Precision=0.2194 | Recall=0.4286 | F1=0.2902
Threshold=0.25 | AUC=0.7496 | Precision=0.2538 | Recall=0.3237 | F1=0.2845
Threshold=0.3 | AUC=0.7496 | Precision=0.2904 | Recall=0.2373 | F1=0.2612
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7538 | Precision=0.1632 | Recall=0.6802 | F1=0.2633
Threshold=0.15 | AUC=0.7538 | Precision=0.2034 | Recall=0.5245 | F1=0.2932
Threshold=0.2 | AUC=0.7538 | Precision=0.2408 | Recall=0.3946 | F1=0.2990
Threshold=0.25 | AUC=0.7538 | Precision=0.2773 | Recall=0.2918 | F1=0.2844
Threshold=0.3 | AUC=0.7538 | Precision=0.3194 | Recall=0.2109 | F1=0.2540
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7412 | Precision=0.1412 | Recall=0.7559 | F1=0.2380
Threshold=0.15 | AUC=0.7412 | Precision=0.1728 | Recall=0.5972 | F1=0.2680
Threshold=0.2 | AUC=0.7412 | Precision=0.2056 | Recall=0.4683 | F1=0.2857
Threshold=0.25 | AUC=0.7412 | Precision=0.2335 | Recall=0.3492 | F1=0.2799
Threshold=0.3 | AUC=0.7412 | Precision=0.2640 | Recall=0.2572 | F1=0.2606
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7481 | Precision=0.1511 | Recall=0.7166 | F1=0.2496
Threshold=0.15 | AUC=0.7481 | Precision=0.1892 | Recall=0.5557 | F1=0.2822
Threshold=0.2 | AUC=0.7481 | Precision=0.2248 | Recall=0.4195 | F1=0.2927
Threshold=0.25 | AUC=0.7481 | Precision=0.2591 | Recall=0.3098 | F1=0.2822
Threshold=0.3 | AUC=0.7481 | Precision=0.2984 | Recall=0.2211 | F1=0.2540
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7521 | Precision=0.1582 | Recall=0.6941 | F1=0.2577
Threshold=0.15 | AUC=0.7521 | Precision=0.1983 | Recall=0.5353 | F1=0.2894
Threshold=0.2 | AUC=0.7521 | Precision=0.2316 | Recall=0.4014 | F1=0.2937
Threshold=0.25 | AUC=0.7521 | Precision=0.2722 | Recall=0.3009 | F1=0.2859
Threshold=0.3 | AUC=0.7521 | Precision=0.3061 | Recall=0.2203 | F1=0.2562
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7556 | Precision=0.1673 | Recall=0.6753 | F1=0.2681
Threshold=0.15 | AUC=0.7556 | Precision=0.2060 | Recall=0.5100 | F1=0.2935
Threshold=0.2 | AUC=0.7556 | Precision=0.2449 | Recall=0.3853 | F1=0.2994
Threshold=0.25 | AUC=0.7556 | Precision=0.2873 | Recall=0.2862 | F1=0.2868
Threshold=0.3 | AUC=0.7556 | Precision=0.3256 | Recall=0.2105 | F1=0.2557
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7533 | Precision=0.1678 | Recall=0.6570 | F1=0.2673
Threshold=0.15 | AUC=0.7533 | Precision=0.2069 | Recall=0.4989 | F1=0.2925
Threshold=0.2 | AUC=0.7533 | Precision=0.2488 | Recall=0.3780 | F1=0.3001
Threshold=0.25 | AUC=0.7533 | Precision=0.2837 | Recall=0.2800 | F1=0.2818
Threshold=0.3 | AUC=0.7533 | Precision=0.3202 | Recall=0.2030 | F1=0.2485
------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7529 | Precision=0.1744 | Recall=0.6276 | F1=0.2730
Threshold=0.15 | AUC=0.7529 | Precision=0.2146 | Recall=0.4737 | F1=0.2954
Threshold=0.2 | AUC=0.7529 | Precision=0.2517 | Recall=0.3561 | F1=0.2949
Threshold=0.25 | AUC=0.7529 | Precision=0.2907 | Recall=0.2671 | F1=0.2784
Threshold=0.3 | AUC=0.7529 | Precision=0.3151 | Recall=0.1917 | F1=0.2384
------------------------------------------

,max_depth,learning_rate,n_estimators,threshold,roc_auc,precision,recall,f1_score
82,8,0.10,200,0.20,0.753269,0.248774,0.378046,0.300080
77,6,0.10,300,0.20,0.755631,0.244880,0.385297,0.299444
57,8,0.05,300,0.20,0.753811,0.240752,0.394562,0.299038
86,8,0.10,300,0.15,0.752940,0.214618,0.473716,0.295403
87,8,0.10,300,0.20,0.752940,0.251673,0.356093,0.294912
27,8,0.03,300,0.20,0.748506,0.217959,0.450755,0.293836
72,6,0.10,200,0.20,0.752101,0.231556,0.401410,0.293693
76,6,0.10,300,0.15,0.755631,0.206021,0.509970,0.293480
56,8,0.05,300,0.15,0.753811,0.203437,0.524471,0.293161
67,4,0.10,300,0.20,0.748082,0.224776,0.419537,0.292721
81,8,0.10,200,0.15,0.753269,0.206882,0.498892,0.292478
47,6,0.05,300,0.20,0.749195,0.220130,0.428600,0.290869
52,8,0.05,200,0.20,0.749610,0.219359,0.428600,0.290195
71,6,0.10,200,0.15,0.752101,0.198343,0.535347,0.289448
28,8,0.03,300,0.25,0.748506,0.250744,0.339174,0.288331
78,6,0.10,300,0.25,0.755631,0.287303,0.286203,0.286752
73,6,0.10,200,0.25,0.752101,0.272230,0.300906,0.285851
62,4,0.10,200,0.20,0.741203,0.205570,0.468278,0.285714
53,8,0.05,200,0.25,0.749610,0.253830,0.323666,0.284525
58,8,0.05,300,0.25,0.753811,0.277321,0.291843,0.284396

In [49]:
# STEP 5 — VIEW BEST RESULTS ⭐⭐⭐
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(

    by="f1_score",

    ascending=False
)

results_df.head(10)

,max_depth,learning_rate,n_estimators,threshold,roc_auc,precision,recall,f1_score
82,8,0.10,200,0.20,0.753269,0.248774,0.378046,0.300080
77,6,0.10,300,0.20,0.755631,0.244880,0.385297,0.299444
57,8,0.05,300,0.20,0.753811,0.240752,0.394562,0.299038
86,8,0.10,300,0.15,0.752940,0.214618,0.473716,0.295403
87,8,0.10,300,0.20,0.752940,0.251673,0.356093,0.294912
27,8,0.03,300,0.20,0.748506,0.217959,0.450755,0.293836
72,6,0.10,200,0.20,0.752101,0.231556,0.401410,0.293693
76,6,0.10,300,0.15,0.755631,0.206021,0.509970,0.293480
56,8,0.05,300,0.15,0.753811,0.203437,0.524471,0.293161
67,4,0.10,300,0.20,0.748082,0.224776,0.419537,0.292721

In [50]:
# TRAIN MULTIPLE MODELS ⭐⭐⭐
# ============================================================
# TRAIN ENSEMBLE MODELS
# ============================================================

model_1 = XGBClassifier(

    max_depth=8,

    learning_rate=0.10,

    n_estimators=200,

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

model_2 = XGBClassifier(

    max_depth=6,

    learning_rate=0.10,

    n_estimators=300,

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

model_3 = XGBClassifier(

    max_depth=8,

    learning_rate=0.05,

    n_estimators=300,

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

# ------------------------------------------------------------
# FIT MODELS
# ------------------------------------------------------------

model_1.fit(
    X_train_resampled,
    y_train_resampled
)

model_2.fit(
    X_train_resampled,
    y_train_resampled
)

model_3.fit(
    X_train_resampled,
    y_train_resampled
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [51]:
# GET PROBABILITIES ⭐⭐⭐
# ============================================================
# PREDICT PROBABILITIES
# ============================================================

prob_1 = model_1.predict_proba(
    X_test
)[:,1]

prob_2 = model_2.predict_proba(
    X_test
)[:,1]

prob_3 = model_3.predict_proba(
    X_test
)[:,1]

In [52]:
# ENSEMBLE AVERAGING ⭐⭐⭐
# ============================================================
# ENSEMBLE PROBABILITIES
# ============================================================

ensemble_probabilities = (

    prob_1
    +
    prob_2
    +
    prob_3

) / 3

In [53]:
# ROC-AUC ⭐⭐⭐
# ============================================================
# ENSEMBLE ROC-AUC
# ============================================================

ensemble_auc = roc_auc_score(

    y_test,

    ensemble_probabilities
)

print(
    f"Ensemble ROC-AUC: {ensemble_auc:.4f}"
)

Ensemble ROC-AUC: 0.7572

In [54]:
# THRESHOLD TESTING ⭐⭐⭐
# ============================================================
# THRESHOLD TESTING
# ============================================================

thresholds = [

    0.10,
    0.15,
    0.20,
    0.25,
    0.30
]

for threshold in thresholds:

    ensemble_predictions = (

        ensemble_probabilities > threshold
    ).astype(int)

    print(f"\nThreshold: {threshold}")

    print(

        classification_report(

            y_test,

            ensemble_predictions
        )
    )

    print("--------------------------------")

Threshold: 0.1
              precision    recall  f1-score   support

           0       0.96      0.70      0.81     56538
           1       0.17      0.68      0.27      4965

    accuracy                           0.70     61503
   macro avg       0.56      0.69      0.54     61503
weighted avg       0.90      0.70      0.77     61503

--------------------------------

Threshold: 0.15
              precision    recall  f1-score   support

           0       0.95      0.83      0.88     56538
           1       0.21      0.51      0.30      4965

    accuracy                           0.80     61503
   macro avg       0.58      0.67      0.59     61503
weighted avg       0.89      0.80      0.84     61503

--------------------------------

Threshold: 0.2
              precision    recall  f1-score   support

           0       0.94      0.90      0.92     56538
           1       0.25      0.39      0.30      4965

    accuracy                           0.86     61503
   macro avg       0.60      0.64      0.61     61503
weighted avg       0.89      0.86      0.87     61503

--------------------------------

Threshold: 0.25
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     56538
           1       0.28      0.28      0.28      4965

    accuracy                           0.88     61503
   macro avg       0.61      0.61      0.61     61503
weighted avg       0.88      0.88      0.88     61503

--------------------------------

Threshold: 0.3
              precision    recall  f1-score   support

           0       0.93      0.96      0.95     56538
           1       0.33      0.21      0.26      4965

    accuracy                           0.90     61503
   macro avg       0.63      0.59      0.60     61503
weighted avg       0.88      0.90      0.89     61503

--------------------------------

In [ ]:
# NOW LOOK AT THE TRADEOFF BEAUTIFULLY ⭐⭐⭐
# THRESHOLD = 0.10
# Metric	Interpretation
# Recall 68%	catch MANY defaults
# Precision 17%	many false alarms

# This behaves like:

# aggressive monitoring system.
# THRESHOLD = 0.20 ⭐⭐⭐
# Metric	Interpretation
# Precision 25%	decent alarm quality
# Recall 39%	meaningful detection

# This is probably:

# your best balanced enterprise setting.
# THRESHOLD = 0.30
# Metric	Interpretation
# Precision 33%	cleaner alerts
# Recall 21%	many defaults missed

# This behaves like:

# conservative approval system.

In [55]:
# SAVE THE BEST 3 MODELS ⭐⭐⭐


import joblib
# SAVE MODEL 1 ⭐⭐⭐
joblib.dump(

    model_1,

    "../models/xgb_model_depth8_lr010_200.pkl"
)
# SAVE MODEL 2 ⭐⭐⭐
joblib.dump(

    model_2,

    "../models/xgb_model_depth6_lr010_300.pkl"
)
# SAVE MODEL 3 ⭐⭐⭐
joblib.dump(

    model_3,

    "../models/xgb_model_depth8_lr005_300.pkl"
)

['../models/xgb_model_depth8_lr005_300.pkl']

In [56]:
# SAVE ENSEMBLE CONFIG ⭐⭐⭐

# VERY enterprise practice.

ensemble_config = {

    "models": [

        "xgb_model_depth8_lr010_200.pkl",

        "xgb_model_depth6_lr010_300.pkl",

        "xgb_model_depth8_lr005_300.pkl"
    ],

    "ensemble_method": "probability_average",

    "recommended_threshold": 0.20
}

joblib.dump(

    ensemble_config,

    "../models/ensemble_config.pkl"
)

['../models/ensemble_config.pkl']

In [57]:
## remove Smote and use average weights

# ============================================================
# LOAD UPDATED ENGINEERED DATASET
# ============================================================

application_train = pd.read_csv(

    "../data/processed/engineered_credit_risk_dataset.csv"
)

application_train.shape

(307511, 169)

In [58]:


# ============================================================
# FEATURE COLUMNS ⭐⭐⭐
# ============================================================

feature_columns = [

    # ========================================================
    # AFFORDABILITY FEATURES
    # ========================================================

    "ANNUITY_TO_INCOME",

    "CREDIT_TO_INCOME",

    "FREE_CASH_FLOW",

    "DEBT_TO_INCOME",

    "CREDIT_TO_ANNUITY_RATIO",

    "CREDIT_TO_GOODS_RATIO",

    "DOWN_PAYMENT",


    # ========================================================
    # EXTERNAL RISK / EXT_SOURCE FEATURES
    # ========================================================

    "EXT_SOURCE_1",

    "EXT_SOURCE_2",

    "EXT_SOURCE_3",

    "EXT_SOURCE_MEAN",

    "EXT_SOURCE_STD",

    "CREDIT_EXT_RATIO",


    # ========================================================
    # LEVERAGE + EXPOSURE FEATURES
    # ========================================================

    "DEBT_PER_BUREAU_RECORD",

    "OVERDUE_PER_BUREAU_RECORD",

    "ACTIVE_DEBT_RATIO",

    "MEAN_DAYS_CREDIT",

    "LAST_ACTIVE_DAYS_CREDIT",


    # ========================================================
    # BORROWING BEHAVIOR FEATURES
    # ========================================================

    "APPLICATIONS_PER_INCOME",

    "PREVIOUS_APPLICATION_COUNT",

    "RECENT_APPLICATION_COUNT",

    "BORROWING_ACCELERATION_RATIO",


    # ========================================================
    # REPAYMENT BEHAVIOR FEATURES
    # ========================================================

    "LATE_PAYMENT_COUNT",

    "MISSED_PAYMENTS_PER_LOAN",

    "AVG_PAYMENT_DELAY",

    "AVG_PAYMENT_DEFICIT",

    "REPAYMENT_STABILITY",


    # ========================================================
    # TEMPORAL REPAYMENT FEATURES
    # ========================================================

    "LATE_PAYMENTS_LAST_90D",

    "AVG_PAYMENT_DELAY_LAST_90D",

    "RECENT_TO_HISTORICAL_DELAY_RATIO",

    "RECENT_DELAY_TREND",

    "RECENT_PAYMENT_DEFICIT",

    "PAYMENT_DEFICIT_TREND",

    "RECENT_PAYMENT_STABILITY",


    # ========================================================
    # EMPLOYMENT + DEMOGRAPHIC FEATURES
    # ========================================================

    "YEARS_EMPLOYED",

    "EMPLOYMENT_TO_AGE_RATIO",

    "AGE_YEARS",


    # ========================================================
    # HISTORICAL REPAYMENT CAPACITY
    # ========================================================

    "MAX_INSTALLMENT",

    "ANNUITY_TO_MAX_INSTALLMENT_RATIO",


    # ========================================================
    # COMPOSITE RISK FEATURES
    # ========================================================

    "BEHAVIORAL_RISK_SCORE"
]


# ============================================================
# TARGET VARIABLE
# ============================================================

target_column = "TARGET"


# ============================================================
# CREATE X AND y
# ============================================================

X = application_train[
    feature_columns
]

y = application_train[
    target_column
]


# ============================================================
# HANDLE MISSING VALUES ⭐⭐⭐
# ============================================================

X = X.fillna(0)


# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)


# ============================================================
# CLASS DISTRIBUTION
# ============================================================

print("\nTRAIN TARGET DISTRIBUTION\n")

print(
    y_train.value_counts()
)


# ============================================================
# SCALE_POS_WEIGHT ⭐⭐⭐
# ============================================================

negative_cases = (

    y_train == 0
).sum()

positive_cases = (

    y_train == 1
).sum()

scale_pos_weight = (

    negative_cases
    /
    positive_cases
)

print(
    f"\nscale_pos_weight = {scale_pos_weight:.2f}"
)


# ============================================================
# TRAIN XGBOOST MODEL ⭐⭐⭐
# ============================================================

from xgboost import XGBClassifier

xgb_model = XGBClassifier(

    max_depth=6,

    learning_rate=0.10,

    n_estimators=300,

    subsample=0.8,

    colsample_bytree=0.8,

    scale_pos_weight=scale_pos_weight,

    random_state=42,

    eval_metric="logloss"
)

xgb_model.fit(

    X_train,

    y_train
)

print(
    "\nXGBoost training completed successfully."
)


# ============================================================
# PREDICT PROBABILITIES
# ============================================================

xgb_probabilities = xgb_model.predict_proba(

    X_test

)[:,1]


# ============================================================
# CUSTOM THRESHOLD ⭐⭐⭐
# ============================================================

threshold = 0.20

xgb_predictions = (

    xgb_probabilities > threshold
).astype(int)


# ============================================================
# CLASSIFICATION REPORT
# ============================================================

from sklearn.metrics import (

    classification_report,

    roc_auc_score,

    confusion_matrix
)

print(
    "\nCLASSIFICATION REPORT\n"
)

print(

    classification_report(

        y_test,

        xgb_predictions
    )
)


# ============================================================
# ROC AUC SCORE
# ============================================================

xgb_auc = roc_auc_score(

    y_test,

    xgb_probabilities
)

print(
    f"\nXGBoost ROC AUC: {xgb_auc:.4f}"
)


# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(

    y_test,

    xgb_predictions
)

print(
    "\nCONFUSION MATRIX\n"
)

print(cm)

TRAIN TARGET DISTRIBUTION

TARGET
0    226148
1     19860
Name: count, dtype: int64

scale_pos_weight = 11.39

XGBoost training completed successfully.

CLASSIFICATION REPORT

              precision    recall  f1-score   support

           0       0.98      0.31      0.47     56538
           1       0.11      0.93      0.19      4965

    accuracy                           0.36     61503
   macro avg       0.54      0.62      0.33     61503
weighted avg       0.91      0.36      0.45     61503


XGBoost ROC AUC: 0.7617

CONFUSION MATRIX

[[17577 38961]
 [  357  4608]]

In [ ]:
# ============================================================
# ENTERPRISE XGBOOST OPTIMIZATION ⭐⭐⭐
# NO SMOTE VERSION
#
# OPTIMIZES:
# - Hyperparameters
# - Thresholds
# - Precision
# - Recall
# - F1
# - ROC-AUC
#
# USING:
# scale_pos_weight
# ============================================================

import pandas as pd
import numpy as np

from xgboost import XGBClassifier

from sklearn.model_selection import (

    train_test_split,

    ParameterGrid
)

from sklearn.metrics import (

    roc_auc_score,

    precision_score,

    recall_score,

    f1_score,

    classification_report,

    confusion_matrix
)


# ============================================================
# LOAD DATASET
# ============================================================

application_train = pd.read_csv(

    "../data/processed/engineered_credit_risk_dataset.csv"
)

print(application_train.shape)


# ============================================================
# FEATURE COLUMNS
# ============================================================

feature_columns = [

    "ANNUITY_TO_INCOME",
    "CREDIT_TO_INCOME",
    "FREE_CASH_FLOW",
    "DEBT_TO_INCOME",
    "CREDIT_TO_ANNUITY_RATIO",
    "CREDIT_TO_GOODS_RATIO",
    "DOWN_PAYMENT",

    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3",
    "EXT_SOURCE_MEAN",
    "EXT_SOURCE_STD",
    "CREDIT_EXT_RATIO",

    "DEBT_PER_BUREAU_RECORD",
    "OVERDUE_PER_BUREAU_RECORD",
    "ACTIVE_DEBT_RATIO",
    "MEAN_DAYS_CREDIT",
    "LAST_ACTIVE_DAYS_CREDIT",

    "APPLICATIONS_PER_INCOME",
    "PREVIOUS_APPLICATION_COUNT",
    "RECENT_APPLICATION_COUNT",
    "BORROWING_ACCELERATION_RATIO",

    "LATE_PAYMENT_COUNT",
    "MISSED_PAYMENTS_PER_LOAN",
    "AVG_PAYMENT_DELAY",
    "AVG_PAYMENT_DEFICIT",
    "REPAYMENT_STABILITY",

    "LATE_PAYMENTS_LAST_90D",
    "AVG_PAYMENT_DELAY_LAST_90D",
    "RECENT_TO_HISTORICAL_DELAY_RATIO",
    "RECENT_DELAY_TREND",
    "RECENT_PAYMENT_DEFICIT",
    "PAYMENT_DEFICIT_TREND",
    "RECENT_PAYMENT_STABILITY",

    "YEARS_EMPLOYED",
    "EMPLOYMENT_TO_AGE_RATIO",
    "AGE_YEARS",

    "MAX_INSTALLMENT",
    "ANNUITY_TO_MAX_INSTALLMENT_RATIO",

    "BEHAVIORAL_RISK_SCORE"
]


# ============================================================
# TARGET
# ============================================================

target_column = "TARGET"

X = application_train[
    feature_columns
].fillna(0)

y = application_train[
    target_column
]


# ============================================================
# TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)


# ============================================================
# SCALE_POS_WEIGHT ⭐⭐⭐
# ============================================================

negative_cases = (

    y_train == 0
).sum()

positive_cases = (

    y_train == 1
).sum()

scale_pos_weight = (

    negative_cases
    /
    positive_cases
)

print(
    f"\nscale_pos_weight = {scale_pos_weight:.2f}"
)


# ============================================================
# HYPERPARAMETER GRID ⭐⭐⭐
# ============================================================

param_grid = {

    "max_depth": [4, 6, 8],

    "learning_rate": [0.03, 0.05, 0.10],

    "n_estimators": [200, 300],

    "subsample": [0.8],

    "colsample_bytree": [0.8],

    "min_child_weight": [1, 3],

    "gamma": [0, 0.2]
}


# ============================================================
# THRESHOLDS ⭐⭐⭐
# IMPORTANT:
# Higher because probabilities shifted upward
# ============================================================

thresholds = [

    0.40,
    0.50,
    0.60,
    0.70,
    0.80
]


# ============================================================
# STORE RESULTS
# ============================================================

results = []


# ============================================================
# HYPERPARAMETER + THRESHOLD SEARCH ⭐⭐⭐
# ============================================================

for params in ParameterGrid(param_grid):

    print(f"\nTesting Parameters: {params}")

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    model = XGBClassifier(

        random_state=42,

        eval_metric="logloss",

        scale_pos_weight=scale_pos_weight,

        **params
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    model.fit(

        X_train,

        y_train
    )

    # --------------------------------------------------------
    # PROBABILITIES
    # --------------------------------------------------------

    probabilities = model.predict_proba(

        X_test

    )[:,1]

    # --------------------------------------------------------
    # ROC AUC
    # --------------------------------------------------------

    auc = roc_auc_score(

        y_test,

        probabilities
    )

    # --------------------------------------------------------
    # TEST THRESHOLDS
    # --------------------------------------------------------

    for threshold in thresholds:

        predictions = (

            probabilities > threshold
        ).astype(int)

        precision = precision_score(

            y_test,

            predictions,

            zero_division=0
        )

        recall = recall_score(

            y_test,

            predictions
        )

        f1 = f1_score(

            y_test,

            predictions
        )

        results.append({

            "max_depth": params["max_depth"],

            "learning_rate": params["learning_rate"],

            "n_estimators": params["n_estimators"],

            "min_child_weight": params["min_child_weight"],

            "gamma": params["gamma"],

            "threshold": threshold,

            "roc_auc": auc,

            "precision": precision,

            "recall": recall,

            "f1_score": f1
        })

        print(

            f"Threshold={threshold} | "
            f"AUC={auc:.4f} | "
            f"Precision={precision:.4f} | "
            f"Recall={recall:.4f} | "
            f"F1={f1:.4f}"
        )

    print(
        "\n----------------------------------------"
    )


# ============================================================
# RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(results)


# ============================================================
# SORT RESULTS ⭐⭐⭐
# ============================================================

results_df = results_df.sort_values(

    by=[

        "f1_score",

        "roc_auc",

        "precision"
    ],

    ascending=False
)

(307511, 169)

scale_pos_weight = 11.39

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7592 | Precision=0.1350 | Recall=0.8123 | F1=0.2315
Threshold=0.5 | AUC=0.7592 | Precision=0.1672 | Recall=0.6862 | F1=0.2689
Threshold=0.6 | AUC=0.7592 | Precision=0.2125 | Recall=0.5343 | F1=0.3041
Threshold=0.7 | AUC=0.7592 | Precision=0.2727 | Recall=0.3406 | F1=0.3029
Threshold=0.8 | AUC=0.7592 | Precision=0.4010 | Recall=0.1289 | F1=0.1951

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7620 | Precision=0.1369 | Recall=0.8062 | F1=0.2340
Threshold=0.5 | AUC=0.7620 | Precision=0.1693 | Recall=0.6886 | F1=0.2718
Threshold=0.6 | AUC=0.7620 | Precision=0.2137 | Recall=0.5416 | F1=0.3064
Threshold=0.7 | AUC=0.7620 | Precision=0.2709 | Recall=0.3557 | F1=0.3076
Threshold=0.8 | AUC=0.7620 | Precision=0.3809 | Recall=0.1505 | F1=0.2157

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7592 | Precision=0.1350 | Recall=0.8123 | F1=0.2315
Threshold=0.5 | AUC=0.7592 | Precision=0.1672 | Recall=0.6862 | F1=0.2689
Threshold=0.6 | AUC=0.7592 | Precision=0.2124 | Recall=0.5343 | F1=0.3040
Threshold=0.7 | AUC=0.7592 | Precision=0.2727 | Recall=0.3406 | F1=0.3029
Threshold=0.8 | AUC=0.7592 | Precision=0.4010 | Recall=0.1289 | F1=0.1951

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7622 | Precision=0.1369 | Recall=0.8062 | F1=0.2341
Threshold=0.5 | AUC=0.7622 | Precision=0.1691 | Recall=0.6878 | F1=0.2715
Threshold=0.6 | AUC=0.7622 | Precision=0.2140 | Recall=0.5426 | F1=0.3070
Threshold=0.7 | AUC=0.7622 | Precision=0.2709 | Recall=0.3549 | F1=0.3073
Threshold=0.8 | AUC=0.7622 | Precision=0.3794 | Recall=0.1505 | F1=0.2155

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7641 | Precision=0.1406 | Recall=0.7976 | F1=0.2391
Threshold=0.5 | AUC=0.7641 | Precision=0.1741 | Recall=0.6749 | F1=0.2768
Threshold=0.6 | AUC=0.7641 | Precision=0.2182 | Recall=0.5293 | F1=0.3090
Threshold=0.7 | AUC=0.7641 | Precision=0.2781 | Recall=0.3466 | F1=0.3086
Threshold=0.8 | AUC=0.7641 | Precision=0.3874 | Recall=0.1448 | F1=0.2108

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7660 | Precision=0.1432 | Recall=0.7911 | F1=0.2425
Threshold=0.5 | AUC=0.7660 | Precision=0.1769 | Recall=0.6691 | F1=0.2798
Threshold=0.6 | AUC=0.7660 | Precision=0.2214 | Recall=0.5307 | F1=0.3124
Threshold=0.7 | AUC=0.7660 | Precision=0.2794 | Recall=0.3529 | F1=0.3119
Threshold=0.8 | AUC=0.7660 | Precision=0.3813 | Recall=0.1563 | F1=0.2217

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7638 | Precision=0.1402 | Recall=0.7966 | F1=0.2385
Threshold=0.5 | AUC=0.7638 | Precision=0.1737 | Recall=0.6721 | F1=0.2761
Threshold=0.6 | AUC=0.7638 | Precision=0.2189 | Recall=0.5309 | F1=0.3100
Threshold=0.7 | AUC=0.7638 | Precision=0.2770 | Recall=0.3478 | F1=0.3084
Threshold=0.8 | AUC=0.7638 | Precision=0.3864 | Recall=0.1448 | F1=0.2107

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7659 | Precision=0.1431 | Recall=0.7899 | F1=0.2423
Threshold=0.5 | AUC=0.7659 | Precision=0.1769 | Recall=0.6701 | F1=0.2799
Threshold=0.6 | AUC=0.7659 | Precision=0.2203 | Recall=0.5275 | F1=0.3108
Threshold=0.7 | AUC=0.7659 | Precision=0.2791 | Recall=0.3535 | F1=0.3119
Threshold=0.8 | AUC=0.7659 | Precision=0.3803 | Recall=0.1565 | F1=0.2217

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7629 | Precision=0.1487 | Recall=0.7561 | F1=0.2485
Threshold=0.5 | AUC=0.7629 | Precision=0.1853 | Recall=0.6342 | F1=0.2868
Threshold=0.6 | AUC=0.7629 | Precision=0.2295 | Recall=0.4860 | F1=0.3118
Threshold=0.7 | AUC=0.7629 | Precision=0.2867 | Recall=0.3114 | F1=0.2985
Threshold=0.8 | AUC=0.7629 | Precision=0.3883 | Recall=0.1319 | F1=0.1969

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7626 | Precision=0.1538 | Recall=0.7400 | F1=0.2546
Threshold=0.5 | AUC=0.7626 | Precision=0.1891 | Recall=0.6173 | F1=0.2896
Threshold=0.6 | AUC=0.7626 | Precision=0.2330 | Recall=0.4757 | F1=0.3128
Threshold=0.7 | AUC=0.7626 | Precision=0.2937 | Recall=0.3110 | F1=0.3021
Threshold=0.8 | AUC=0.7626 | Precision=0.3942 | Recall=0.1396 | F1=0.2062

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7633 | Precision=0.1492 | Recall=0.7605 | F1=0.2494
Threshold=0.5 | AUC=0.7633 | Precision=0.1853 | Recall=0.6361 | F1=0.2870
Threshold=0.6 | AUC=0.7633 | Precision=0.2293 | Recall=0.4854 | F1=0.3115
Threshold=0.7 | AUC=0.7633 | Precision=0.2875 | Recall=0.3106 | F1=0.2986
Threshold=0.8 | AUC=0.7633 | Precision=0.3971 | Recall=0.1345 | F1=0.2010

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7623 | Precision=0.1540 | Recall=0.7440 | F1=0.2552
Threshold=0.5 | AUC=0.7623 | Precision=0.1899 | Recall=0.6197 | F1=0.2907
Threshold=0.6 | AUC=0.7623 | Precision=0.2331 | Recall=0.4747 | F1=0.3127
Threshold=0.7 | AUC=0.7623 | Precision=0.2899 | Recall=0.3059 | F1=0.2977
Threshold=0.8 | AUC=0.7623 | Precision=0.3967 | Recall=0.1408 | F1=0.2078

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7622 | Precision=0.1374 | Recall=0.8042 | F1=0.2347
Threshold=0.5 | AUC=0.7622 | Precision=0.1693 | Recall=0.6842 | F1=0.2714
Threshold=0.6 | AUC=0.7622 | Precision=0.2140 | Recall=0.5444 | F1=0.3072
Threshold=0.7 | AUC=0.7622 | Precision=0.2712 | Recall=0.3605 | F1=0.3095
Threshold=0.8 | AUC=0.7622 | Precision=0.3751 | Recall=0.1581 | F1=0.2224

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7651 | Precision=0.1391 | Recall=0.8008 | F1=0.2371
Threshold=0.5 | AUC=0.7651 | Precision=0.1716 | Recall=0.6810 | F1=0.2741
Threshold=0.6 | AUC=0.7651 | Precision=0.2170 | Recall=0.5458 | F1=0.3105
Threshold=0.7 | AUC=0.7651 | Precision=0.2737 | Recall=0.3664 | F1=0.3133
Threshold=0.8 | AUC=0.7651 | Precision=0.3675 | Recall=0.1674 | F1=0.2300

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7627 | Precision=0.1372 | Recall=0.8048 | F1=0.2345
Threshold=0.5 | AUC=0.7627 | Precision=0.1695 | Recall=0.6866 | F1=0.2719
Threshold=0.6 | AUC=0.7627 | Precision=0.2146 | Recall=0.5470 | F1=0.3083
Threshold=0.7 | AUC=0.7627 | Precision=0.2718 | Recall=0.3617 | F1=0.3104
Threshold=0.8 | AUC=0.7627 | Precision=0.3767 | Recall=0.1579 | F1=0.2225

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7657 | Precision=0.1394 | Recall=0.8018 | F1=0.2376
Threshold=0.5 | AUC=0.7657 | Precision=0.1721 | Recall=0.6850 | F1=0.2751
Threshold=0.6 | AUC=0.7657 | Precision=0.2176 | Recall=0.5462 | F1=0.3112
Threshold=0.7 | AUC=0.7657 | Precision=0.2728 | Recall=0.3656 | F1=0.3124
Threshold=0.8 | AUC=0.7657 | Precision=0.3691 | Recall=0.1662 | F1=0.2292

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7658 | Precision=0.1436 | Recall=0.7851 | F1=0.2428
Threshold=0.5 | AUC=0.7658 | Precision=0.1782 | Recall=0.6697 | F1=0.2815
Threshold=0.6 | AUC=0.7658 | Precision=0.2227 | Recall=0.5297 | F1=0.3136
Threshold=0.7 | AUC=0.7658 | Precision=0.2816 | Recall=0.3553 | F1=0.3142
Threshold=0.8 | AUC=0.7658 | Precision=0.3795 | Recall=0.1623 | F1=0.2274

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7664 | Precision=0.1471 | Recall=0.7754 | F1=0.2472
Threshold=0.5 | AUC=0.7664 | Precision=0.1811 | Recall=0.6582 | F1=0.2841
Threshold=0.6 | AUC=0.7664 | Precision=0.2262 | Recall=0.5208 | F1=0.3154
Threshold=0.7 | AUC=0.7664 | Precision=0.2843 | Recall=0.3531 | F1=0.3149
Threshold=0.8 | AUC=0.7664 | Precision=0.3766 | Recall=0.1641 | F1=0.2286

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7655 | Precision=0.1434 | Recall=0.7831 | F1=0.2424
Threshold=0.5 | AUC=0.7655 | Precision=0.1777 | Recall=0.6657 | F1=0.2805
Threshold=0.6 | AUC=0.7655 | Precision=0.2235 | Recall=0.5325 | F1=0.3148
Threshold=0.7 | AUC=0.7655 | Precision=0.2794 | Recall=0.3543 | F1=0.3124
Threshold=0.8 | AUC=0.7655 | Precision=0.3781 | Recall=0.1605 | F1=0.2254

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7662 | Precision=0.1471 | Recall=0.7734 | F1=0.2472
Threshold=0.5 | AUC=0.7662 | Precision=0.1811 | Recall=0.6560 | F1=0.2839
Threshold=0.6 | AUC=0.7662 | Precision=0.2257 | Recall=0.5204 | F1=0.3148
Threshold=0.7 | AUC=0.7662 | Precision=0.2842 | Recall=0.3549 | F1=0.3156
Threshold=0.8 | AUC=0.7662 | Precision=0.3783 | Recall=0.1660 | F1=0.2307

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7626 | Precision=0.1555 | Recall=0.7339 | F1=0.2567
Threshold=0.5 | AUC=0.7626 | Precision=0.1921 | Recall=0.6131 | F1=0.2925
Threshold=0.6 | AUC=0.7626 | Precision=0.2338 | Recall=0.4699 | F1=0.3123
Threshold=0.7 | AUC=0.7626 | Precision=0.2923 | Recall=0.3074 | F1=0.2996
Threshold=0.8 | AUC=0.7626 | Precision=0.3864 | Recall=0.1422 | F1=0.2079

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7600 | Precision=0.1611 | Recall=0.7069 | F1=0.2624
Threshold=0.5 | AUC=0.7600 | Precision=0.1982 | Recall=0.5879 | F1=0.2964
Threshold=0.6 | AUC=0.7600 | Precision=0.2382 | Recall=0.4471 | F1=0.3108
Threshold=0.7 | AUC=0.7600 | Precision=0.2984 | Recall=0.2914 | F1=0.2949
Threshold=0.8 | AUC=0.7600 | Precision=0.3956 | Recall=0.1382 | F1=0.2048

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7636 | Precision=0.1561 | Recall=0.7372 | F1=0.2576
Threshold=0.5 | AUC=0.7636 | Precision=0.1932 | Recall=0.6179 | F1=0.2944
Threshold=0.6 | AUC=0.7636 | Precision=0.2346 | Recall=0.4727 | F1=0.3136
Threshold=0.7 | AUC=0.7636 | Precision=0.2913 | Recall=0.3094 | F1=0.3001
Threshold=0.8 | AUC=0.7636 | Precision=0.3889 | Recall=0.1420 | F1=0.2080

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7616 | Precision=0.1625 | Recall=0.7150 | F1=0.2648
Threshold=0.5 | AUC=0.7616 | Precision=0.1993 | Recall=0.5930 | F1=0.2984
Threshold=0.6 | AUC=0.7616 | Precision=0.2408 | Recall=0.4518 | F1=0.3142
Threshold=0.7 | AUC=0.7616 | Precision=0.2986 | Recall=0.2951 | F1=0.2968
Threshold=0.8 | AUC=0.7616 | Precision=0.3916 | Recall=0.1368 | F1=0.2027

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7660 | Precision=0.1421 | Recall=0.8014 | F1=0.2414
Threshold=0.5 | AUC=0.7660 | Precision=0.1731 | Recall=0.6773 | F1=0.2758
Threshold=0.6 | AUC=0.7660 | Precision=0.2171 | Recall=0.5436 | F1=0.3102
Threshold=0.7 | AUC=0.7660 | Precision=0.2742 | Recall=0.3726 | F1=0.3159
Threshold=0.8 | AUC=0.7660 | Precision=0.3651 | Recall=0.1784 | F1=0.2397

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7665 | Precision=0.1435 | Recall=0.7952 | F1=0.2432
Threshold=0.5 | AUC=0.7665 | Precision=0.1756 | Recall=0.6723 | F1=0.2784
Threshold=0.6 | AUC=0.7665 | Precision=0.2187 | Recall=0.5362 | F1=0.3107
Threshold=0.7 | AUC=0.7665 | Precision=0.2764 | Recall=0.3690 | F1=0.3161
Threshold=0.8 | AUC=0.7665 | Precision=0.3640 | Recall=0.1791 | F1=0.2400

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7646 | Precision=0.1409 | Recall=0.7990 | F1=0.2396
Threshold=0.5 | AUC=0.7646 | Precision=0.1722 | Recall=0.6765 | F1=0.2746
Threshold=0.6 | AUC=0.7646 | Precision=0.2163 | Recall=0.5424 | F1=0.3093
Threshold=0.7 | AUC=0.7646 | Precision=0.2713 | Recall=0.3678 | F1=0.3122
Threshold=0.8 | AUC=0.7646 | Precision=0.3694 | Recall=0.1762 | F1=0.2386

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7661 | Precision=0.1426 | Recall=0.7932 | F1=0.2417
Threshold=0.5 | AUC=0.7661 | Precision=0.1752 | Recall=0.6715 | F1=0.2779
Threshold=0.6 | AUC=0.7661 | Precision=0.2178 | Recall=0.5347 | F1=0.3095
Threshold=0.7 | AUC=0.7661 | Precision=0.2742 | Recall=0.3646 | F1=0.3130
Threshold=0.8 | AUC=0.7661 | Precision=0.3693 | Recall=0.1821 | F1=0.2439

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7633 | Precision=0.1492 | Recall=0.7633 | F1=0.2497
Threshold=0.5 | AUC=0.7633 | Precision=0.1825 | Recall=0.6491 | F1=0.2849
Threshold=0.6 | AUC=0.7633 | Precision=0.2218 | Recall=0.5082 | F1=0.3088
Threshold=0.7 | AUC=0.7633 | Precision=0.2788 | Recall=0.3426 | F1=0.3074
Threshold=0.8 | AUC=0.7633 | Precision=0.3693 | Recall=0.1662 | F1=0.2292

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7617 | Precision=0.1545 | Recall=0.7428 | F1=0.2558
Threshold=0.5 | AUC=0.7617 | Precision=0.1869 | Recall=0.6254 | F1=0.2878
Threshold=0.6 | AUC=0.7617 | Precision=0.2266 | Recall=0.4886 | F1=0.3096
Threshold=0.7 | AUC=0.7617 | Precision=0.2822 | Recall=0.3311 | F1=0.3047
Threshold=0.8 | AUC=0.7617 | Precision=0.3745 | Recall=0.1680 | F1=0.2319

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7636 | Precision=0.1499 | Recall=0.7621 | F1=0.2505
Threshold=0.5 | AUC=0.7636 | Precision=0.1832 | Recall=0.6491 | F1=0.2858
Threshold=0.6 | AUC=0.7636 | Precision=0.2233 | Recall=0.5110 | F1=0.3108
Threshold=0.7 | AUC=0.7636 | Precision=0.2812 | Recall=0.3531 | F1=0.3131
Threshold=0.8 | AUC=0.7636 | Precision=0.3688 | Recall=0.1758 | F1=0.2381

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7605 | Precision=0.1538 | Recall=0.7422 | F1=0.2548
Threshold=0.5 | AUC=0.7605 | Precision=0.1872 | Recall=0.6266 | F1=0.2882
Threshold=0.6 | AUC=0.7605 | Precision=0.2252 | Recall=0.4862 | F1=0.3078
Threshold=0.7 | AUC=0.7605 | Precision=0.2851 | Recall=0.3396 | F1=0.3100
Threshold=0.8 | AUC=0.7605 | Precision=0.3708 | Recall=0.1706 | F1=0.2337

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7527 | Precision=0.1646 | Recall=0.6775 | F1=0.2648
Threshold=0.5 | AUC=0.7527 | Precision=0.1982 | Recall=0.5609 | F1=0.2928
Threshold=0.6 | AUC=0.7527 | Precision=0.2364 | Recall=0.4234 | F1=0.3034
Threshold=0.7 | AUC=0.7527 | Precision=0.2952 | Recall=0.2836 | F1=0.2893
Threshold=0.8 | AUC=0.7527 | Precision=0.3763 | Recall=0.1347 | F1=0.1984

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7466 | Precision=0.1764 | Recall=0.6348 | F1=0.2761
Threshold=0.5 | AUC=0.7466 | Precision=0.2088 | Recall=0.5132 | F1=0.2969
Threshold=0.6 | AUC=0.7466 | Precision=0.2424 | Recall=0.3766 | F1=0.2950
Threshold=0.7 | AUC=0.7466 | Precision=0.3031 | Recall=0.2534 | F1=0.2760
Threshold=0.8 | AUC=0.7466 | Precision=0.3730 | Recall=0.1200 | F1=0.1816

----------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.4 | AUC=0.7530 | Precision=0.1648 | Recall=0.6781 | F1=0.2651
Threshold=0.5 | AUC=0.7530 | Precision=0.1987 | Recall=0.5585 | F1=0.2931
Threshold=0.6 | AUC=0.7530 | Precision=0.2423 | Recall=0.4346 | F1=0.3111
Threshold=0.7 | AUC=0.7530 | Precision=0.2941 | Recall=0.2860 | F1=0.2900

In [60]:

# ============================================================
# TOP RESULTS
# ============================================================

print(
    "\nTOP 20 RESULTS\n"
)

print(

    results_df.head(20)
)


# ============================================================
# BEST MODEL CONFIG ⭐⭐⭐
# ============================================================

best_result = results_df.iloc[0]

print(
    "\nBEST CONFIGURATION\n"
)

print(best_result)

TOP 20 RESULTS

     max_depth  learning_rate  n_estimators  min_child_weight  gamma  \
292          8           0.05           200                 3    0.2
128          4           0.10           300                 1    0.0
308          4           0.10           300                 1    0.2
297          8           0.05           300                 3    0.2
123          4           0.10           200                 1    0.0
303          4           0.10           200                 1    0.2
98           6           0.05           300                 3    0.0
268          6           0.05           300                 1    0.2
87           6           0.05           300                 1    0.0
277          6           0.05           300                 3    0.2
88           6           0.05           300                 1    0.0
97           6           0.05           300                 3    0.0
92           6           0.05           200                 3    0.0
272          6           0.05           200                 3    0.2
263          6           0.05           200                 1    0.2
117          8           0.05           300                 3    0.0
83           6           0.05           200                 1    0.0
267          6           0.05           300                 1    0.2
278          6           0.05           300                 3    0.2
218          6           0.03           300                 3    0.2

     threshold   roc_auc  precision    recall  f1_score
292        0.6  0.763666   0.237409  0.477543  0.317148
128        0.7  0.766469   0.276403  0.368983  0.316053
308        0.7  0.766750   0.275883  0.369789  0.316007
297        0.6  0.761611   0.242291  0.454179  0.316003
123        0.7  0.765981   0.274155  0.372608  0.315888
303        0.7  0.765969   0.274155  0.372608  0.315888
98         0.7  0.766247   0.284194  0.354884  0.315629
268        0.7  0.766479   0.284925  0.353273  0.315439
87         0.6  0.766429   0.226207  0.520846  0.315424
277        0.6  0.765781   0.225947  0.521249  0.315245
88         0.7  0.766429   0.284255  0.353072  0.314948
97         0.6  0.766247   0.225677  0.520443  0.314834
92         0.6  0.765499   0.223462  0.532528  0.314818
272        0.6  0.765498   0.223462  0.532528  0.314818
263        0.7  0.765765   0.281569  0.355690  0.314319
117        0.6  0.761605   0.240846  0.451762  0.314190
83         0.7  0.765848   0.281564  0.355287  0.314159
267        0.6  0.766479   0.225022  0.519839  0.314086
278        0.7  0.765781   0.283126  0.352467  0.314014
218        0.7  0.765392   0.280304  0.356294  0.313764

BEST CONFIGURATION

max_depth             8.000000
learning_rate         0.050000
n_estimators        200.000000
min_child_weight      3.000000
gamma                 0.200000
threshold             0.600000
roc_auc               0.763666
precision             0.237409
recall                0.477543
f1_score              0.317148
Name: 292, dtype: float64

In [ ]:
# ============================================================
# ENTERPRISE CREDIT RISK PIPELINE ⭐⭐⭐
# SMOTEENN / SMOTETOMEK + XGBOOST
#
# Includes:
# - imbalance handling
# - hyperparameter optimization
# - threshold optimization
# - ROC-AUC
# - Precision
# - Recall
# - F1
# - confusion matrix
#
# ENTERPRISE-GRADE MODELING PIPELINE
# ============================================================


# ============================================================
# IMPORTS
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import (

    train_test_split,

    ParameterGrid
)

from sklearn.metrics import (

    roc_auc_score,

    precision_score,

    recall_score,

    f1_score,

    classification_report,

    confusion_matrix
)

from xgboost import XGBClassifier


# ============================================================
# LOAD DATASET
# ============================================================

application_train = pd.read_csv(

    "../data/processed/engineered_credit_risk_dataset.csv"
)

print(
    application_train.shape
)


# ============================================================
# FEATURE COLUMNS ⭐⭐⭐
# ============================================================

feature_columns = [

    # AFFORDABILITY

    "ANNUITY_TO_INCOME",

    "CREDIT_TO_INCOME",

    "FREE_CASH_FLOW",

    "DEBT_TO_INCOME",

    "CREDIT_TO_ANNUITY_RATIO",

    "CREDIT_TO_GOODS_RATIO",

    "DOWN_PAYMENT",

    # EXT_SOURCE

    "EXT_SOURCE_1",

    "EXT_SOURCE_2",

    "EXT_SOURCE_3",

    "EXT_SOURCE_MEAN",

    "EXT_SOURCE_STD",

    "CREDIT_EXT_RATIO",

    # LEVERAGE

    "DEBT_PER_BUREAU_RECORD",

    "OVERDUE_PER_BUREAU_RECORD",

    "ACTIVE_DEBT_RATIO",

    "MEAN_DAYS_CREDIT",

    "LAST_ACTIVE_DAYS_CREDIT",

    # BORROWING

    "APPLICATIONS_PER_INCOME",

    "PREVIOUS_APPLICATION_COUNT",

    "RECENT_APPLICATION_COUNT",

    "BORROWING_ACCELERATION_RATIO",

    # REPAYMENT

    "LATE_PAYMENT_COUNT",

    "MISSED_PAYMENTS_PER_LOAN",

    "AVG_PAYMENT_DELAY",

    "AVG_PAYMENT_DEFICIT",

    "REPAYMENT_STABILITY",

    # TEMPORAL

    "LATE_PAYMENTS_LAST_90D",

    "AVG_PAYMENT_DELAY_LAST_90D",

    "RECENT_TO_HISTORICAL_DELAY_RATIO",

    "RECENT_DELAY_TREND",

    "RECENT_PAYMENT_DEFICIT",

    "PAYMENT_DEFICIT_TREND",

    "RECENT_PAYMENT_STABILITY",

    # EMPLOYMENT

    "YEARS_EMPLOYED",

    "EMPLOYMENT_TO_AGE_RATIO",

    "AGE_YEARS",

    # HISTORICAL CAPACITY

    "MAX_INSTALLMENT",

    "ANNUITY_TO_MAX_INSTALLMENT_RATIO",

    # COMPOSITE

    "BEHAVIORAL_RISK_SCORE"
]


# ============================================================
# TARGET
# ============================================================

target_column = "TARGET"

X = application_train[
    feature_columns
]

y = application_train[
    target_column
]

X = X.fillna(0)


# ============================================================
# TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

print(
    "\nOriginal Train Distribution\n"
)

print(
    y_train.value_counts()
)


# ============================================================
# CHOOSE RESAMPLING METHOD ⭐⭐⭐
# ============================================================

USE_SMOTEENN = True

USE_SMOTETOMEK = False


# ============================================================
# SMOTEENN ⭐⭐⭐
# ============================================================

if USE_SMOTEENN:

    from imblearn.combine import SMOTEENN

    print(
        "\nUsing SMOTEENN\n"
    )

    resampler = SMOTEENN(

        random_state=42
    )

    X_train_resampled, y_train_resampled = (

        resampler.fit_resample(

            X_train,

            y_train
        )
    )


# ============================================================
# SMOTETOMEK ⭐⭐⭐
# ============================================================

elif USE_SMOTETOMEK:

    from imblearn.combine import SMOTETomek

    print(
        "\nUsing SMOTETomek\n"
    )

    resampler = SMOTETomek(

        random_state=42
    )

    X_train_resampled, y_train_resampled = (

        resampler.fit_resample(

            X_train,

            y_train
        )
    )


# ============================================================
# RESAMPLED DISTRIBUTION
# ============================================================

print(
    "\nResampled Distribution\n"
)

print(
    y_train_resampled.value_counts()
)


# ============================================================
# XGBOOST PARAMETER GRID ⭐⭐⭐
# ============================================================

param_grid = {

    "max_depth": [4, 6, 8],

    "learning_rate": [0.03, 0.05, 0.10],

    "n_estimators": [200, 300],

    "subsample": [0.8],

    "colsample_bytree": [0.8],

    "min_child_weight": [1, 3],

    "gamma": [0, 0.2]
}


# ============================================================
# THRESHOLDS ⭐⭐⭐
# ============================================================

thresholds = [

    0.10,

    0.15,

    0.20,

    0.25,

    0.30,

    0.40,

    0.50
]


# ============================================================
# STORE RESULTS
# ============================================================

results = []


# ============================================================
# HYPERPARAMETER SEARCH ⭐⭐⭐
# ============================================================

for params in ParameterGrid(param_grid):

    print(
        f"\nTesting Parameters: {params}"
    )

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    model = XGBClassifier(

        random_state=42,

        eval_metric="logloss",

        **params
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    model.fit(

        X_train_resampled,

        y_train_resampled
    )

    # --------------------------------------------------------
    # PREDICT PROBABILITIES
    # --------------------------------------------------------

    probabilities = model.predict_proba(

        X_test

    )[:,1]

    # --------------------------------------------------------
    # ROC AUC
    # --------------------------------------------------------

    auc = roc_auc_score(

        y_test,

        probabilities
    )

    # --------------------------------------------------------
    # THRESHOLD TESTING
    # --------------------------------------------------------

    for threshold in thresholds:

        predictions = (

            probabilities > threshold
        ).astype(int)

        precision = precision_score(

            y_test,

            predictions,

            zero_division=0
        )

        recall = recall_score(

            y_test,

            predictions
        )

        f1 = f1_score(

            y_test,

            predictions
        )

        results.append({

            "max_depth": params["max_depth"],

            "learning_rate": params["learning_rate"],

            "n_estimators": params["n_estimators"],

            "min_child_weight": params["min_child_weight"],

            "gamma": params["gamma"],

            "threshold": threshold,

            "roc_auc": auc,

            "precision": precision,

            "recall": recall,

            "f1_score": f1
        })

        print(

            f"Threshold={threshold} | "
            f"AUC={auc:.4f} | "
            f"Precision={precision:.4f} | "
            f"Recall={recall:.4f} | "
            f"F1={f1:.4f}"
        )

    print(
        "\n-------------------------------------------"
    )


# ============================================================
# RESULTS DATAFRAME ⭐⭐⭐
# ============================================================

results_df = pd.DataFrame(results)


# ============================================================
# SORT RESULTS
# ============================================================

results_df = results_df.sort_values(

    by=[

        "f1_score",

        "roc_auc",

        "precision"
    ],

    ascending=False
)


# ============================================================
# TOP RESULTS
# ============================================================

print(
    "\nTOP 20 RESULTS\n"
)

print(

    results_df.head(20)
)


# ============================================================
# BEST MODEL CONFIG ⭐⭐⭐
# ============================================================

best_result = results_df.iloc[0]

print(
    "\nBEST CONFIGURATION\n"
)

print(best_result)

(307511, 169)

Original Train Distribution

TARGET
0    226148
1     19860
Name: count, dtype: int64

Using SMOTEENN


Resampled Distribution

TARGET
1    203356
0    142298
Name: count, dtype: int64

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7291 | Precision=0.0930 | Recall=0.9635 | F1=0.1696
Threshold=0.15 | AUC=0.7291 | Precision=0.1071 | Recall=0.8975 | F1=0.1914
Threshold=0.2 | AUC=0.7291 | Precision=0.1216 | Recall=0.8222 | F1=0.2119
Threshold=0.25 | AUC=0.7291 | Precision=0.1365 | Recall=0.7505 | F1=0.2310
Threshold=0.3 | AUC=0.7291 | Precision=0.1500 | Recall=0.6739 | F1=0.2454
Threshold=0.4 | AUC=0.7291 | Precision=0.1776 | Recall=0.5327 | F1=0.2664
Threshold=0.5 | AUC=0.7291 | Precision=0.2128 | Recall=0.3879 | F1=0.2748

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7339 | Precision=0.1027 | Recall=0.9255 | F1=0.1849
Threshold=0.15 | AUC=0.7339 | Precision=0.1201 | Recall=0.8356 | F1=0.2100
Threshold=0.2 | AUC=0.7339 | Precision=0.1374 | Recall=0.7559 | F1=0.2326
Threshold=0.25 | AUC=0.7339 | Precision=0.1529 | Recall=0.6745 | F1=0.2493
Threshold=0.3 | AUC=0.7339 | Precision=0.1692 | Recall=0.6006 | F1=0.2640
Threshold=0.4 | AUC=0.7339 | Precision=0.1995 | Recall=0.4499 | F1=0.2765
Threshold=0.5 | AUC=0.7339 | Precision=0.2406 | Recall=0.3086 | F1=0.2704

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7291 | Precision=0.0930 | Recall=0.9635 | F1=0.1696
Threshold=0.15 | AUC=0.7291 | Precision=0.1071 | Recall=0.8975 | F1=0.1914
Threshold=0.2 | AUC=0.7291 | Precision=0.1216 | Recall=0.8222 | F1=0.2119
Threshold=0.25 | AUC=0.7291 | Precision=0.1365 | Recall=0.7505 | F1=0.2310
Threshold=0.3 | AUC=0.7291 | Precision=0.1500 | Recall=0.6739 | F1=0.2454
Threshold=0.4 | AUC=0.7291 | Precision=0.1776 | Recall=0.5327 | F1=0.2664
Threshold=0.5 | AUC=0.7291 | Precision=0.2128 | Recall=0.3879 | F1=0.2748

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7338 | Precision=0.1025 | Recall=0.9251 | F1=0.1846
Threshold=0.15 | AUC=0.7338 | Precision=0.1201 | Recall=0.8365 | F1=0.2101
Threshold=0.2 | AUC=0.7338 | Precision=0.1372 | Recall=0.7545 | F1=0.2322
Threshold=0.25 | AUC=0.7338 | Precision=0.1524 | Recall=0.6735 | F1=0.2485
Threshold=0.3 | AUC=0.7338 | Precision=0.1692 | Recall=0.6004 | F1=0.2640
Threshold=0.4 | AUC=0.7338 | Precision=0.1997 | Recall=0.4504 | F1=0.2767
Threshold=0.5 | AUC=0.7338 | Precision=0.2404 | Recall=0.3082 | F1=0.2701

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7375 | Precision=0.1053 | Recall=0.9212 | F1=0.1890
Threshold=0.15 | AUC=0.7375 | Precision=0.1244 | Recall=0.8191 | F1=0.2160
Threshold=0.2 | AUC=0.7375 | Precision=0.1428 | Recall=0.7297 | F1=0.2388
Threshold=0.25 | AUC=0.7375 | Precision=0.1619 | Recall=0.6506 | F1=0.2592
Threshold=0.3 | AUC=0.7375 | Precision=0.1764 | Recall=0.5619 | F1=0.2685
Threshold=0.4 | AUC=0.7375 | Precision=0.2118 | Recall=0.4123 | F1=0.2798
Threshold=0.5 | AUC=0.7375 | Precision=0.2522 | Recall=0.2711 | F1=0.2613

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7437 | Precision=0.1172 | Recall=0.8711 | F1=0.2066
Threshold=0.15 | AUC=0.7437 | Precision=0.1397 | Recall=0.7631 | F1=0.2361
Threshold=0.2 | AUC=0.7437 | Precision=0.1602 | Recall=0.6653 | F1=0.2582
Threshold=0.25 | AUC=0.7437 | Precision=0.1793 | Recall=0.5722 | F1=0.2730
Threshold=0.3 | AUC=0.7437 | Precision=0.1991 | Recall=0.4937 | F1=0.2837
Threshold=0.4 | AUC=0.7437 | Precision=0.2385 | Recall=0.3438 | F1=0.2816
Threshold=0.5 | AUC=0.7437 | Precision=0.2853 | Recall=0.2224 | F1=0.2499

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7376 | Precision=0.1054 | Recall=0.9241 | F1=0.1893
Threshold=0.15 | AUC=0.7376 | Precision=0.1242 | Recall=0.8197 | F1=0.2157
Threshold=0.2 | AUC=0.7376 | Precision=0.1433 | Recall=0.7311 | F1=0.2396
Threshold=0.25 | AUC=0.7376 | Precision=0.1624 | Recall=0.6532 | F1=0.2601
Threshold=0.3 | AUC=0.7376 | Precision=0.1767 | Recall=0.5633 | F1=0.2690
Threshold=0.4 | AUC=0.7376 | Precision=0.2110 | Recall=0.4099 | F1=0.2786
Threshold=0.5 | AUC=0.7376 | Precision=0.2528 | Recall=0.2709 | F1=0.2615

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7439 | Precision=0.1169 | Recall=0.8713 | F1=0.2062
Threshold=0.15 | AUC=0.7439 | Precision=0.1393 | Recall=0.7646 | F1=0.2356
Threshold=0.2 | AUC=0.7439 | Precision=0.1601 | Recall=0.6663 | F1=0.2582
Threshold=0.25 | AUC=0.7439 | Precision=0.1797 | Recall=0.5746 | F1=0.2738
Threshold=0.3 | AUC=0.7439 | Precision=0.1980 | Recall=0.4914 | F1=0.2823
Threshold=0.4 | AUC=0.7439 | Precision=0.2400 | Recall=0.3438 | F1=0.2827
Threshold=0.5 | AUC=0.7439 | Precision=0.2878 | Recall=0.2228 | F1=0.2511

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7441 | Precision=0.1159 | Recall=0.8790 | F1=0.2049
Threshold=0.15 | AUC=0.7441 | Precision=0.1383 | Recall=0.7702 | F1=0.2345
Threshold=0.2 | AUC=0.7441 | Precision=0.1588 | Recall=0.6715 | F1=0.2568
Threshold=0.25 | AUC=0.7441 | Precision=0.1796 | Recall=0.5815 | F1=0.2744
Threshold=0.3 | AUC=0.7441 | Precision=0.1981 | Recall=0.4951 | F1=0.2830
Threshold=0.4 | AUC=0.7441 | Precision=0.2403 | Recall=0.3482 | F1=0.2844
Threshold=0.5 | AUC=0.7441 | Precision=0.2814 | Recall=0.2238 | F1=0.2493

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7500 | Precision=0.1270 | Recall=0.8330 | F1=0.2205
Threshold=0.15 | AUC=0.7500 | Precision=0.1520 | Recall=0.7140 | F1=0.2507
Threshold=0.2 | AUC=0.7500 | Precision=0.1755 | Recall=0.6105 | F1=0.2726
Threshold=0.25 | AUC=0.7500 | Precision=0.2007 | Recall=0.5251 | F1=0.2904
Threshold=0.3 | AUC=0.7500 | Precision=0.2211 | Recall=0.4373 | F1=0.2937
Threshold=0.4 | AUC=0.7500 | Precision=0.2651 | Recall=0.3009 | F1=0.2819
Threshold=0.5 | AUC=0.7500 | Precision=0.3116 | Recall=0.1927 | F1=0.2382

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7444 | Precision=0.1155 | Recall=0.8806 | F1=0.2042
Threshold=0.15 | AUC=0.7444 | Precision=0.1379 | Recall=0.7712 | F1=0.2340
Threshold=0.2 | AUC=0.7444 | Precision=0.1582 | Recall=0.6707 | F1=0.2561
Threshold=0.25 | AUC=0.7444 | Precision=0.1793 | Recall=0.5821 | F1=0.2742
Threshold=0.3 | AUC=0.7444 | Precision=0.1980 | Recall=0.4975 | F1=0.2833
Threshold=0.4 | AUC=0.7444 | Precision=0.2396 | Recall=0.3474 | F1=0.2836
Threshold=0.5 | AUC=0.7444 | Precision=0.2831 | Recall=0.2250 | F1=0.2507

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7499 | Precision=0.1274 | Recall=0.8369 | F1=0.2211
Threshold=0.15 | AUC=0.7499 | Precision=0.1520 | Recall=0.7156 | F1=0.2507
Threshold=0.2 | AUC=0.7499 | Precision=0.1760 | Recall=0.6145 | F1=0.2736
Threshold=0.25 | AUC=0.7499 | Precision=0.2009 | Recall=0.5303 | F1=0.2914
Threshold=0.3 | AUC=0.7499 | Precision=0.2194 | Recall=0.4361 | F1=0.2920
Threshold=0.4 | AUC=0.7499 | Precision=0.2658 | Recall=0.2997 | F1=0.2817
Threshold=0.5 | AUC=0.7499 | Precision=0.3087 | Recall=0.1919 | F1=0.2367

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7341 | Precision=0.1052 | Recall=0.9172 | F1=0.1888
Threshold=0.15 | AUC=0.7341 | Precision=0.1230 | Recall=0.8220 | F1=0.2139
Threshold=0.2 | AUC=0.7341 | Precision=0.1406 | Recall=0.7382 | F1=0.2362
Threshold=0.25 | AUC=0.7341 | Precision=0.1568 | Recall=0.6564 | F1=0.2531
Threshold=0.3 | AUC=0.7341 | Precision=0.1718 | Recall=0.5758 | F1=0.2647
Threshold=0.4 | AUC=0.7341 | Precision=0.2035 | Recall=0.4250 | F1=0.2752
Threshold=0.5 | AUC=0.7341 | Precision=0.2496 | Recall=0.2926 | F1=0.2694

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7398 | Precision=0.1146 | Recall=0.8785 | F1=0.2028
Threshold=0.15 | AUC=0.7398 | Precision=0.1350 | Recall=0.7740 | F1=0.2299
Threshold=0.2 | AUC=0.7398 | Precision=0.1556 | Recall=0.6810 | F1=0.2534
Threshold=0.25 | AUC=0.7398 | Precision=0.1735 | Recall=0.5869 | F1=0.2679
Threshold=0.3 | AUC=0.7398 | Precision=0.1906 | Recall=0.5033 | F1=0.2765
Threshold=0.4 | AUC=0.7398 | Precision=0.2328 | Recall=0.3593 | F1=0.2825
Threshold=0.5 | AUC=0.7398 | Precision=0.2792 | Recall=0.2352 | F1=0.2553

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7345 | Precision=0.1058 | Recall=0.9164 | F1=0.1897
Threshold=0.15 | AUC=0.7345 | Precision=0.1242 | Recall=0.8236 | F1=0.2158
Threshold=0.2 | AUC=0.7345 | Precision=0.1416 | Recall=0.7370 | F1=0.2375
Threshold=0.25 | AUC=0.7345 | Precision=0.1568 | Recall=0.6502 | F1=0.2527
Threshold=0.3 | AUC=0.7345 | Precision=0.1721 | Recall=0.5718 | F1=0.2645
Threshold=0.4 | AUC=0.7345 | Precision=0.2052 | Recall=0.4250 | F1=0.2767
Threshold=0.5 | AUC=0.7345 | Precision=0.2491 | Recall=0.2896 | F1=0.2678

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7402 | Precision=0.1153 | Recall=0.8773 | F1=0.2038
Threshold=0.15 | AUC=0.7402 | Precision=0.1360 | Recall=0.7704 | F1=0.2313
Threshold=0.2 | AUC=0.7402 | Precision=0.1566 | Recall=0.6753 | F1=0.2542
Threshold=0.25 | AUC=0.7402 | Precision=0.1746 | Recall=0.5809 | F1=0.2685
Threshold=0.3 | AUC=0.7402 | Precision=0.1929 | Recall=0.4975 | F1=0.2780
Threshold=0.4 | AUC=0.7402 | Precision=0.2353 | Recall=0.3519 | F1=0.2820
Threshold=0.5 | AUC=0.7402 | Precision=0.2818 | Recall=0.2292 | F1=0.2528

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7447 | Precision=0.1195 | Recall=0.8606 | F1=0.2099
Threshold=0.15 | AUC=0.7447 | Precision=0.1429 | Recall=0.7523 | F1=0.2401
Threshold=0.2 | AUC=0.7447 | Precision=0.1640 | Recall=0.6542 | F1=0.2623
Threshold=0.25 | AUC=0.7447 | Precision=0.1855 | Recall=0.5664 | F1=0.2795
Threshold=0.3 | AUC=0.7447 | Precision=0.2015 | Recall=0.4733 | F1=0.2827
Threshold=0.4 | AUC=0.7447 | Precision=0.2457 | Recall=0.3351 | F1=0.2835
Threshold=0.5 | AUC=0.7447 | Precision=0.2889 | Recall=0.2133 | F1=0.2454

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7506 | Precision=0.1287 | Recall=0.8322 | F1=0.2229
Threshold=0.15 | AUC=0.7506 | Precision=0.1542 | Recall=0.7134 | F1=0.2536
Threshold=0.2 | AUC=0.7506 | Precision=0.1774 | Recall=0.6058 | F1=0.2744
Threshold=0.25 | AUC=0.7506 | Precision=0.2019 | Recall=0.5140 | F1=0.2899
Threshold=0.3 | AUC=0.7506 | Precision=0.2232 | Recall=0.4320 | F1=0.2944
Threshold=0.4 | AUC=0.7506 | Precision=0.2673 | Recall=0.2926 | F1=0.2794
Threshold=0.5 | AUC=0.7506 | Precision=0.3253 | Recall=0.1927 | F1=0.2421

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7449 | Precision=0.1201 | Recall=0.8590 | F1=0.2108
Threshold=0.15 | AUC=0.7449 | Precision=0.1429 | Recall=0.7450 | F1=0.2398
Threshold=0.2 | AUC=0.7449 | Precision=0.1647 | Recall=0.6471 | F1=0.2625
Threshold=0.25 | AUC=0.7449 | Precision=0.1850 | Recall=0.5549 | F1=0.2775
Threshold=0.3 | AUC=0.7449 | Precision=0.2034 | Recall=0.4699 | F1=0.2839
Threshold=0.4 | AUC=0.7449 | Precision=0.2500 | Recall=0.3295 | F1=0.2843
Threshold=0.5 | AUC=0.7449 | Precision=0.2965 | Recall=0.2113 | F1=0.2467

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7509 | Precision=0.1285 | Recall=0.8312 | F1=0.2226
Threshold=0.15 | AUC=0.7509 | Precision=0.1533 | Recall=0.7063 | F1=0.2519
Threshold=0.2 | AUC=0.7509 | Precision=0.1783 | Recall=0.6050 | F1=0.2755
Threshold=0.25 | AUC=0.7509 | Precision=0.2012 | Recall=0.5102 | F1=0.2885
Threshold=0.3 | AUC=0.7509 | Precision=0.2252 | Recall=0.4272 | F1=0.2949
Threshold=0.4 | AUC=0.7509 | Precision=0.2711 | Recall=0.2902 | F1=0.2803
Threshold=0.5 | AUC=0.7509 | Precision=0.3224 | Recall=0.1889 | F1=0.2383

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7510 | Precision=0.1293 | Recall=0.8203 | F1=0.2234
Threshold=0.15 | AUC=0.7510 | Precision=0.1559 | Recall=0.7021 | F1=0.2551
Threshold=0.2 | AUC=0.7510 | Precision=0.1802 | Recall=0.5984 | F1=0.2770
Threshold=0.25 | AUC=0.7510 | Precision=0.2041 | Recall=0.5063 | F1=0.2909
Threshold=0.3 | AUC=0.7510 | Precision=0.2258 | Recall=0.4216 | F1=0.2941
Threshold=0.4 | AUC=0.7510 | Precision=0.2741 | Recall=0.2888 | F1=0.2813
Threshold=0.5 | AUC=0.7510 | Precision=0.3111 | Recall=0.1875 | F1=0.2340

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7551 | Precision=0.1373 | Recall=0.7948 | F1=0.2342
Threshold=0.15 | AUC=0.7551 | Precision=0.1651 | Recall=0.6705 | F1=0.2650
Threshold=0.2 | AUC=0.7551 | Precision=0.1919 | Recall=0.5706 | F1=0.2872
Threshold=0.25 | AUC=0.7551 | Precision=0.2173 | Recall=0.4800 | F1=0.2992
Threshold=0.3 | AUC=0.7551 | Precision=0.2412 | Recall=0.4012 | F1=0.3013
Threshold=0.4 | AUC=0.7551 | Precision=0.2869 | Recall=0.2709 | F1=0.2787
Threshold=0.5 | AUC=0.7551 | Precision=0.3378 | Recall=0.1813 | F1=0.2359

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7521 | Precision=0.1300 | Recall=0.8232 | F1=0.2245
Threshold=0.15 | AUC=0.7521 | Precision=0.1564 | Recall=0.7027 | F1=0.2559
Threshold=0.2 | AUC=0.7521 | Precision=0.1807 | Recall=0.5952 | F1=0.2772
Threshold=0.25 | AUC=0.7521 | Precision=0.2058 | Recall=0.5110 | F1=0.2934
Threshold=0.3 | AUC=0.7521 | Precision=0.2275 | Recall=0.4262 | F1=0.2966
Threshold=0.4 | AUC=0.7521 | Precision=0.2734 | Recall=0.2902 | F1=0.2816
Threshold=0.5 | AUC=0.7521 | Precision=0.3165 | Recall=0.1897 | F1=0.2372

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7557 | Precision=0.1363 | Recall=0.7966 | F1=0.2327
Threshold=0.15 | AUC=0.7557 | Precision=0.1652 | Recall=0.6735 | F1=0.2653
Threshold=0.2 | AUC=0.7557 | Precision=0.1919 | Recall=0.5710 | F1=0.2872
Threshold=0.25 | AUC=0.7557 | Precision=0.2186 | Recall=0.4844 | F1=0.3012
Threshold=0.3 | AUC=0.7557 | Precision=0.2407 | Recall=0.4012 | F1=0.3009
Threshold=0.4 | AUC=0.7557 | Precision=0.2826 | Recall=0.2685 | F1=0.2754
Threshold=0.5 | AUC=0.7557 | Precision=0.3338 | Recall=0.1811 | F1=0.2348

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7439 | Precision=0.1219 | Recall=0.8475 | F1=0.2132
Threshold=0.15 | AUC=0.7439 | Precision=0.1468 | Recall=0.7388 | F1=0.2450
Threshold=0.2 | AUC=0.7439 | Precision=0.1687 | Recall=0.6290 | F1=0.2660
Threshold=0.25 | AUC=0.7439 | Precision=0.1894 | Recall=0.5339 | F1=0.2796
Threshold=0.3 | AUC=0.7439 | Precision=0.2093 | Recall=0.4506 | F1=0.2858
Threshold=0.4 | AUC=0.7439 | Precision=0.2526 | Recall=0.3086 | F1=0.2778
Threshold=0.5 | AUC=0.7439 | Precision=0.2997 | Recall=0.2004 | F1=0.2402

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7493 | Precision=0.1282 | Recall=0.8272 | F1=0.2220
Threshold=0.15 | AUC=0.7493 | Precision=0.1546 | Recall=0.7100 | F1=0.2539
Threshold=0.2 | AUC=0.7493 | Precision=0.1792 | Recall=0.5998 | F1=0.2759
Threshold=0.25 | AUC=0.7493 | Precision=0.2033 | Recall=0.5033 | F1=0.2896
Threshold=0.3 | AUC=0.7493 | Precision=0.2256 | Recall=0.4205 | F1=0.2936
Threshold=0.4 | AUC=0.7493 | Precision=0.2693 | Recall=0.2804 | F1=0.2747
Threshold=0.5 | AUC=0.7493 | Precision=0.3208 | Recall=0.1835 | F1=0.2334

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 200, 'subsample': 0.8}
Threshold=0.1 | AUC=0.7440 | Precision=0.1218 | Recall=0.8504 | F1=0.2131
Threshold=0.15 | AUC=0.7440 | Precision=0.1466 | Recall=0.7398 | F1=0.2446
Threshold=0.2 | AUC=0.7440 | Precision=0.1684 | Recall=0.6296 | F1=0.2658
Threshold=0.25 | AUC=0.7440 | Precision=0.1886 | Recall=0.5325 | F1=0.2785
Threshold=0.3 | AUC=0.7440 | Precision=0.2087 | Recall=0.4479 | F1=0.2847
Threshold=0.4 | AUC=0.7440 | Precision=0.2515 | Recall=0.3090 | F1=0.2773
Threshold=0.5 | AUC=0.7440 | Precision=0.3004 | Recall=0.2018 | F1=0.2414

-------------------------------------------

Testing Parameters: {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 300, 'subsample': 0.8}

In [64]:

# ============================================================
# RETRAIN BEST MODEL ⭐⭐⭐
# ============================================================

best_model = XGBClassifier(

    max_depth=int(best_result["max_depth"]),

    learning_rate=float(
        best_result["learning_rate"]
    ),

    n_estimators=int(
        best_result["n_estimators"]
    ),

    min_child_weight=int(
        best_result["min_child_weight"]
    ),

    gamma=float(
        best_result["gamma"]
    ),

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

best_model.fit(

    X_train_resampled,

    y_train_resampled
)


# ============================================================
# FINAL PREDICTIONS ⭐⭐⭐
# ============================================================

best_threshold = float(
    best_result["threshold"]
)

final_probabilities = best_model.predict_proba(

    X_test

)[:,1]

final_predictions = (

    final_probabilities > best_threshold
).astype(int)


# ============================================================
# FINAL CLASSIFICATION REPORT
# ============================================================

print(
    "\nFINAL CLASSIFICATION REPORT\n"
)

print(

    classification_report(

        y_test,

        final_predictions
    )
)

FINAL CLASSIFICATION REPORT

              precision    recall  f1-score   support

           0       0.94      0.89      0.92     56538
           1       0.24      0.41      0.30      4965

    accuracy                           0.85     61503
   macro avg       0.59      0.65      0.61     61503
weighted avg       0.89      0.85      0.87     61503

In [65]:

# ============================================================
# FINAL ROC AUC
# ============================================================

final_auc = roc_auc_score(

    y_test,

    final_probabilities
)

print(
    f"\nFINAL ROC AUC: {final_auc:.4f}"
)


# ============================================================
# FINAL CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(

    y_test,

    final_predictions
)

print(
    "\nFINAL CONFUSION MATRIX\n"
)

print(cm)

FINAL ROC AUC: 0.7544

FINAL CONFUSION MATRIX

[[50218  6320]
 [ 2950  2015]]

In [66]:
# ============================================================
# SAVE FINAL PRODUCTION MODEL ⭐⭐⭐
# ============================================================

import joblib

# ------------------------------------------------------------
# SAVE BEST MODEL
# ------------------------------------------------------------

joblib.dump(

    best_model,

    "../models/final_credit_risk_xgboost_model.pkl"
)

print(
    "Final model saved successfully."
)


# ============================================================
# SAVE FEATURE LIST ⭐⭐⭐
# ============================================================

joblib.dump(

    feature_columns,

    "../models/final_feature_columns.pkl"
)

print(
    "Feature column list saved successfully."
)


# ============================================================
# SAVE FINAL THRESHOLD ⭐⭐⭐
# ============================================================

joblib.dump(

    best_threshold,

    "../models/final_threshold.pkl"
)

print(
    "Final threshold saved successfully."
)


# ============================================================
# SAVE MODEL METADATA ⭐⭐⭐
# ============================================================

model_metadata = {

    "model_type": "XGBoost",

    "resampling_strategy": "SMOTEENN",

    "roc_auc": 0.7544,

    "precision": 0.24,

    "recall": 0.41,

    "f1_score": 0.30,

    "threshold": best_threshold,

    "business_purpose": (

        "Credit risk ranking and "
        "early warning prioritization"
    )
}

joblib.dump(

    model_metadata,

    "../models/final_model_metadata.pkl"
)

print(
    "Model metadata saved successfully."
)

Final model saved successfully.
Feature column list saved successfully.
Final threshold saved successfully.
Model metadata saved successfully.